src/cli.ts
This fixes the compatibility with NPM 6 because it passed the `--` over to our CLI.
Repro: `npm init playwright@latest -- --quiet --browser=chromium`
NPM version: 6
Relates https://github.com/microsoft/playwright-vscode/issues/120 (main issue is different, thats why not closing)
=> fix: ignore unrecognizable cli parameters

.github/workflows/ci.yml, playwright.config.ts, tests/integration.spec.ts
The Playwright Test version inside the repository is pinned - this means like we installed the dependencies of the pinned version (GitHub workflow yml).
Since Playwright evolves -> more dependencies get added over time. This diverges with the actual Playwright version inside the tests -> latest. This change calls install-deps inside the tests too. An alternative approach would be #12 but this seems nicer.
=> test: fix tests

assets/example.spec.ts
```txt
➜  extensiontstest npx tsc                                                                                    
src/example.spec.ts:390:59 - error TS7006: Parameter 'i' implicitly has an 'any' type.
390     return JSON.parse(localStorage['react-todos']).filter(i => i.completed).length === e;
~
src/example.spec.ts:396:56 - error TS7006: Parameter 'i' implicitly has an 'any' type.
396     return JSON.parse(localStorage['react-todos']).map(i => i.title).includes(t);
~
Found 2 errors in the same file, starting at: src/example.spec.ts:390
```
=> chore: fix compatible with default TypeScript config

assets/github-actions.yml
Change name of `npx playwright install` GitHub actions step. I think that "Install Playwright" isn't quite accurate because playwright was already installed in the previous step. What this step is actually doing is installing the browsers.
=> Change name GitHub actions step

src/cli.ts, src/generator.ts, tests/integration.spec.ts
Fixes https://github.com/microsoft/playwright/issues/17374
Not sure if its worth adding a test.
=> chore: add install no browsers prompt

assets/example.spec.js, assets/example.spec.ts
update examples to align with new docs example just released: 
https://playwright.dev/docs/writing-tests
=> chore: update examples

src/packageManager.ts
Whether to run `pnpm dlx` or `pnpm exec` should depend on whether to run the package from the registry or from local `node_modules`:
- [`pnpm dlx`](https://pnpm.io/cli/dlx) will always download from the npm registry
- [`pnpm exec`](https://pnpm.io/cli/exec) will run the package from `node_modules`
(In contrary, npm’s `npx` will run the package from local `node_modules` if it exists, only install otherwise. This is not the behavior of `pnpm dlx`.)
So it should be something like this:
- Use `pnpm dlx` to run `create-playwright`
- Use `pnpm exec` to run `playwright`
=> Use pnpm exec instead of pnpm dlx

README.md
`pnpm` has the [same API](https://pnpm.io/cli/create) as yarn: `pnpm create`
=> docs: `pnpm` usage fix

src/generator.ts, tests/integration.spec.ts
This will replace `@types/node` dependency in `@playwright/test`.
=> feat: install @types/node

src/generator.ts
The Playwright v1.37 introduces the new `merge-reports` command.
This uses blob files created within the `blob-reports` directory, but this directory is not included within the gitignore file, and will be committed to git when you're not paying attention to it.
This PR adds the `blob-reports` directory to the gitignore file.
=> feat: add blob-report to gitignore

src/generator.ts, src/packageManager.ts, tests/integration.spec.ts
Fixes https://github.com/microsoft/playwright/issues/27203.
=> feat: support running in the root of pnpm workspace

assets/playwright.config.js, assets/playwright.config.ts
https://github.com/microsoft/playwright/issues/31145
The default is `Default: path.resolve(process.cwd(), '.env')` which is a problem for us in monorepo scenarios.
=> chore: absolute dotenv path import

src/cli.ts
Hi there, I was reading the code for the `--help` flag and I realized that `create-playwright` is:
1. Exiting with a non-zero exit code
2. Doing some work to find the root directory and then throwing that away
Both of these seem like unusual patterns.
Some basis for the return code 0 change here:
- https://stackoverflow.com/questions/50565408/should-bash-scripts-called-with-help-argument-return-0-or-not-zero-exit-code
=> fix: exit with return code 0, exit early with --help

package-lock.json, package.json, src/generator.ts, src/packageManager.ts, tests/integration.spec.ts
When initializing playwright in an existing project, the CLI miss `package-lock=false` in the .npmrc (if exists).
`npm ci` is not compatible without lockfile, this PR fixes it: when package-lock.json is disabled, replaces `npm ci` with `npm i` in the workflow.
=> feat: handle disabled lockfile

src/generator.ts, tests/integration.spec.ts
This PR fixes the duplication of existing `.gitignore` entries while running `npm create playwright`. 
Although this only occurs when the command is run more than once, the added entries don't need to be duplicated. 
Related to https://github.com/microsoft/playwright/issues/31021
=> fix: don't duplicate `.gitignore` entries

package.json
The current link to the github repo in the package.json is incorrect, which makes it easier to find the source code for the package. This PR fixes it
=> fix: correct repository link in package.json

assets/demo-todo-app.spec.js, assets/example.spec.js, assets/playwright-ct.config.js, assets/playwright.config.js
We transform everything which allows us to use `import` in JS files. This means we don't need to feature detect esm/cjs on the create-playwright side and can emit `import` all the time.
This follows our strategy to only show TS examples in the docs, since they match JS in most of the cases % types.
Closes https://github.com/microsoft/playwright/issues/33238
=> chore: use import instead of require in generated JS examples

src/generator.ts, tests/integration.spec.ts
closes https://github.com/microsoft/playwright/issues/33307.
=> feat: section header when appending existing `.gitignore`

src/packageManager.ts, tests/integration.spec.ts
Fixes https://github.com/microsoft/playwright/issues/34370
=> fix: install in the root of yarn workspaces

.github/workflows/ci.yml, playwright.config.ts, tests/baseFixtures.ts, tests/component-testing.spec.ts, tests/integration.spec.ts
Follow-up to https://github.com/microsoft/create-playwright/pull/138. Because the implementation hard-codes which Yarn it calls, there's no to test both yarn versions in parallel. This somehow slipped the last PR.
This PR changes it so that we have two separate ones, and we change the global yarn version in between.
=> test: execute one yarn after another

.github/workflows/ci.yml, tests/integration.spec.ts
The current `yarn set version stable` only installs yarn berry inside the repository. But since tests are running in $TMP, they're not subject to that. Using corepack was the only way I could find to install Yarn berry globally. I've updated tests to ensure that.
=> fix: install yarn berry globally

src/packageManager.ts, tests/baseFixtures.ts, tests/integration.spec.ts
Resolves https://github.com/microsoft/playwright/issues/34805
=> fix(yarn): only pass -W to yarn classic

.github/workflows/publish.yml
Similar to how we do it upstream: https://github.com/microsoft/playwright/blob/e2c8163b145d4a34f4585fc11a8a2643b9c94f98/utils/publish_all_packages.sh#L97
Reference: https://docs.npmjs.com/generating-provenance-statements
=> devops: use `--provenance` when publishing to NPM

.github/workflows/publish.yml
Like [upstream](https://github.com/microsoft/playwright/blob/3ad5c2731a3ccccbd8468ef14a88b1edd45867a4/.github/workflows/publish_release_npm.yml#L15) and in the [docs](https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow).
=> devops: fix npm publishing due to proverance

package.json
Fixes https://github.com/microsoft/create-playwright/actions/runs/15213460958/job/42793133179#step:5:47
Problem: different capitalisation.
drive-by: align the way we pass the metadata like we do upstream.
=> chore: adjust package.json > repository metadata

tests/integration.spec.ts
This won't spam the stdout/stderr anymore and put it as an annotation instead like we do for the other tests.
=> test: migrate to exec fixture

assets/playwright.config.js, assets/playwright.config.ts
Othewise it may cause confusion if the user puts something like https://demo.playwright.dev/todomvc/#/ in the base url and wants to navigate to that exact url by default.
=> chore: use relative path in the comment for the baseURL
